name: Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@V28
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update flake.lock
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          nix flake update --commit-lock-file

      - name: Generate commit message
        id: commit
        run: |
          echo 'message<<PRMESSAGE' >> "${GITHUB_OUTPUT}"
          git log -1 --pretty=%B | tail +3 | awk -f ./scripts/flake-to-markdown.awk >> "${GITHUB_OUTPUT}"
          echo 'PRMESSAGE' >> "${GITHUB_OUTPUT}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update flake.lock
          body: "${{ steps.commit.outputs.message }}"
          labels: automated
          branch: automated/update-flake
          delete-branch: true
